# Site settings
title: Divish's blog
email: 
description: "Musings of a Data Scientist."
baseurl: ""
url: "http://karpathy.github.io"
twitter_username: divishdayal
github_username:  divishdayal

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
syntax_highlighter: rouge